'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  DownloadPretrained:
    resources:
      instance-type: C5
    outputs:
      pretrainedNetwork:
        type: dataset
        with:
          ref: diffusion-laion-laion2b_s12b_b42k
    uses: container@v1
    with:
      image: alpine:latest
      args:
        - wget 
        - https://huggingface.co/laion/CLIP-ViT-g-14-laion2B-s12B-b42K/resolve/main/open_clip_pytorch_model.bin
        - -P
        - /outputs/pretrainedNetwork/
