'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: P4000
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        # 1. 复制一份代码到 $HOME/repo（home 是可写的）
        cp -r /inputs/repo $HOME/repo
        cd $HOME/repo
  
        # 2. 让你的下载/缓存目录都在 home 里
        export OPENAI_CLIP_HOME=$HOME/repo/Diffusion/laion/laion2b_s12b_b42k
        mkdir -p $OPENAI_CLIP_HOME
        
        pip install -r requirements.txt
        python run_gaussian_shading.py \
          --jpeg_ratio 30 \
          --fpr 0.000001 \
          --channel_copy 1 \
          --hw_copy 8 \
          --chacha 1 \
          --num 2 \
          --reference_model ViT-g-14 \
          --reference_model_pretrain laion2b_s12b_b42k
      image: paperspace/gradient-base:pt112-tf29-jax0317-py39-20230125
