'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  getPretrainedModelCats:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: dataset
        with:
          ref: diffusion-laion-laion2b_s12b_b42k
    uses: container@v1
    with:
      args:
        - wget
        - https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/stylegan2-cat-config-f.pkl
        - -P
        - /outputs/pretrainedNetwork
      image: alpine:latest
