'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: P4000
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      repo:
        type: volume
    uses: script@v1
    with:
      script: |-
        ls -ld .                     
        ls -ld /inputs/repo          
        ls -ld /outputs              
        ls -ld /outputs/repo         
        ls -la /outputs              
        
        echo testing > ./test.txt    && echo "cwd writable" || echo "cwd not writable"
        echo testing > /inputs/repo/test.txt \
                                      && echo "/inputs/repo writable" \
                                      || echo "/inputs/repo not writable"
        echo testing > /outputs/repo/x.txt \
                                      && echo "/outputs/repo writable" \
                                      || echo "/outputs/repo not writable"

      image: paperspace/gradient-base:pt112-tf29-jax0317-py39-20230125
