'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
    uses: git-checkout@v1
    with:
      url: context.event.github.url
