'on':
  github:
    branches:
      only: main
jobs:
  getPretrainedModelCats:
    resources:
      instance-type: C5
    outputs:
      pretrainedNetwork:
        type: dataset
        with:
          ref: demo-dataset
    uses: container@v1
    with:
      args:
        - wget
        - https://huggingface.co/laion/CLIP-ViT-g-14-laion2B-s12B-b42K/resolve/main/open_clip_pytorch_model.bin
        - -P
        - /outputs/pretrainedNetwork
      image: alpine:latest
