'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: P4000
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      model_cache:
        type: volume
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        cp -r . /outputs/model_cache/repo
        cd /outputs/model_cache/repo
        pwd
        ls -ld .
        ls -ld .
        mkdir -p /outputs/model_cache/repo/Diffusion/laion/laion2b_s12b_b42k
        pip install -r requirements.txt
        python run_gaussian_shading.py \
          --jpeg_ratio 30 \
          --fpr 0.000001 \
          --channel_copy 1 \
          --hw_copy 8 \
          --chacha 1 \
          --num 2 \
          --reference_model ViT-g-14 \
          --reference_model_pretrain laion2b_s12b_b42k
      image: paperspace/gradient-base:pt112-tf29-jax0317-py39-20230125
